model_list:
  - model_name: ai-angelo-zero
    litellm_params:
      model: ollama/llama3.2
      api_base: "http://host.docker.internal:11434"
      drop_params: True
      temperature: 0

guardrails:
  - guardrail_name: "pii-masking"
    litellm_params:
      guardrail: presidio
      mode: "pre_call"
      default_on: true
      presidio_analyzer_api_base: "http://presidio-analyzer:3000"
      presidio_anonymizer_api_base: "http://presidio-anonymizer:3000"
      presidio_ad_hoc_recognizers: "/app/presidio_ad_hoc_recognizers.json"
      output_parse_pii: false
      presidio_language: "en"
